{
 "title": "Idempotent Payment API Dashboard",
 "tags": [
  "go-app",
  "observability"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "App Logs (Loki)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "{job=\"go-app\"}"
    }
   ]
  },
  {
   "title": "Total Payment Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "targets": [
    { "expr": "payment_requests_total" }
   ]
  },
  {
   "title": "Failed Payment Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "targets": [
    { "expr": "payment_requests_failed" }
   ]
  }
 ]
}